/** Reference-aligned learning shell for the backend-connected quiz flow. */
import { FilePlus2, LibraryBig, ListChecks, Menu, Settings2, X } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { Brand } from "./Brand";

const railNav = [["Upload", "/upload", FilePlus2], ["Generate", "/quiz-settings", Settings2], ["Questions", "/questions", LibraryBig], ["Quiz", "/quiz", ListChecks]] as const;
const topNav = [["Upload PDF", "/upload"], ["Generate MCQs", "/quiz-settings"], ["Review Questions", "/questions"], ["Take Quiz", "/quiz"]] as const;

export function AppShell({ children, title, kicker, action }: { children: React.ReactNode; title: string; kicker?: string; action?: React.ReactNode }) {
  const [location] = useLocation(); const [open, setOpen] = useState(false);
  const rail = <aside className="reference-rail flex h-full w-[82px] flex-col items-center border-r border-[#E3E0D7] bg-[#F4F2EE] py-6"><div className="mb-9"><Brand compact /></div><nav className="flex flex-1 flex-col items-center gap-2" aria-label="Workspace navigation">{railNav.map(([label, href, Icon]) => <Link key={label} href={href} onClick={() => setOpen(false)} title={label} className={`rail-link ${location === href ? "active" : ""}`}><Icon className="h-[18px] w-[18px]" /><span className="sr-only">{label}</span></Link>)}</nav></aside>;
  return <div className="reference-body min-h-screen bg-[#D4D5CF] p-0 text-[#30312D] lg:p-6"><div className="reference-window min-h-screen overflow-hidden bg-[#F2F1ED] lg:min-h-[calc(100vh-3rem)] lg:rounded-[2rem] lg:border lg:border-white/70 lg:shadow-[0_25px_80px_rgba(53,58,51,.16)]"><div className="fixed inset-0 z-40 hidden bg-[#30312D]/20 backdrop-blur-sm" style={{ display: open ? "block" : "none" }} onClick={() => setOpen(false)} /><div className={`fixed inset-y-0 left-0 z-50 -translate-x-full transition-transform duration-300 lg:relative lg:float-left lg:translate-x-0 ${open ? "translate-x-0" : ""}`}>{rail}<button onClick={() => setOpen(false)} className="absolute right-[-2.8rem] top-4 grid h-9 w-9 place-items-center rounded-full bg-white shadow lg:hidden" aria-label="Close menu"><X className="h-4 w-4" /></button></div><main className="min-h-screen lg:ml-[82px]"><header className="reference-header flex min-h-[92px] items-center gap-5 px-5 sm:px-8"><button onClick={() => setOpen(true)} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white shadow-sm lg:hidden" aria-label="Open menu"><Menu className="h-5 w-5" /></button><div className="min-w-0 lg:hidden"><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-[#758164]">{kicker || "Learning workspace"}</p><h1 className="truncate font-display text-2xl tracking-[-.04em]">{title}</h1></div><nav className="reference-pill-nav mx-auto hidden items-center justify-center gap-1 lg:flex" aria-label="Learning sections">{topNav.map(([label, href]) => <Link key={label} href={href} className={`reference-top-link ${location === href ? "active" : ""}`}>{label}</Link>)}</nav><div className="ml-auto flex items-center gap-2">{action}</div></header><div className="reference-canvas px-5 pb-8 sm:px-8 lg:px-10 lg:pb-10"><div className="reference-page-heading hidden lg:block"><p>{kicker || "Learning workspace"}</p><h1>{title}</h1></div>{children}</div></main></div></div>;
}
