/** Scholarly Current design: a notebook workbench that makes progress legible through paper-like cards, cobalt signals, and calm space. */
import { motion, useInView } from "framer-motion";
import { ArrowRight, BookOpen, Clock3, FilePlus2, GraduationCap, ListChecks, Target, TrendingUp } from "lucide-react";
import { useRef } from "react";
import { Link } from "wouter";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/AppShell";
import { CourseCard, ProgressCircle, SectionKicker } from "@/components/LearningComponents";
import { courses, performanceData, topicData, weeklyActivity } from "@/data/mockData";

function AnimatedNumber({ value, suffix = "" }: { value: number; suffix?: string }) {
  const ref = useRef<HTMLSpanElement>(null); const visible = useInView(ref, { once: true });
  return <span ref={ref}>{visible ? value : 0}{suffix}</span>;
}
function StatCard({ icon: Icon, label, value, note, accent }: { icon: typeof BookOpen; label: string; value: number; note: string; accent: string }) {
  return <motion.article initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} whileHover={{ y: -3 }} className="stat-card"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl" style={{ backgroundColor: `${accent}16`, color: accent }}><Icon className="h-5 w-5" /></span><span className="text-xs font-bold text-[#21867E]">+12% week</span></div><p className="mt-7 text-xs font-bold uppercase tracking-[.12em] text-[#65728A]">{label}</p><p className="mt-1 font-display text-4xl tracking-[-.06em] text-[#18233B]"><AnimatedNumber value={value} suffix={label === "Average score" ? "%" : ""} /></p><p className="mt-2 text-xs text-[#65728A]">{note}</p></motion.article>;
}
export default function Dashboard() {
  return <AppShell title="Good morning, Alex." kicker="Ready to learn?" action={<Link href="/upload" className="btn-primary hidden sm:inline-flex"><FilePlus2 className="h-4 w-4" /> Create New Quiz</Link>}>
    <div className="dashboard-grid">
      <section className="lg:col-span-2"><div className="flex items-end justify-between gap-4"><div><SectionKicker>Learning overview</SectionKicker><h2 className="font-display text-3xl tracking-[-.045em]">Your practice is adding up.</h2></div><Link href="/analytics" className="btn-quiet hidden sm:inline-flex">View analytics <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={GraduationCap} label="Courses / Subjects" value={4} note="Active this term" accent="#3B63E8" /><StatCard icon={ListChecks} label="Quizzes completed" value={24} note="3 more than last week" accent="#7667D8" /><StatCard icon={Target} label="Questions practiced" value={486} note="Across all subjects" accent="#2D9C95" /><StatCard icon={TrendingUp} label="Average score" value={87} note="A steady improvement" accent="#D28C49" /></div></section>
      <motion.aside initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} className="study-goal-card lg:row-span-2"><SectionKicker>This week</SectionKicker><div className="mt-3 flex items-center justify-between"><div><h2 className="font-display text-3xl tracking-[-.045em]">Keep your rhythm.</h2><p className="mt-2 max-w-[15rem] text-sm leading-6 text-[#65728A]">Two focused sessions will complete your study goal.</p></div><ProgressCircle value={72} size={86} /></div><div className="mt-8 border-t border-[#DCE4F6] pt-5"><div className="flex justify-between text-sm"><span className="font-semibold text-[#53617A]">Study time</span><strong>4h 18m / 6h</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><motion.div initial={{ width: 0 }} whileInView={{ width: "72%" }} viewport={{ once: true }} transition={{ duration: .7 }} className="h-full rounded-full bg-[#3B63E8]" /></div></div></motion.aside>
      <section className="lg:col-span-2"><div className="mt-3 flex items-end justify-between"><div><SectionKicker>Continue learning</SectionKicker><h2 className="font-display text-3xl tracking-[-.045em]">Pick up where you left off.</h2></div><Link href="/resources" className="text-sm font-bold text-[#3B63E8]">All subjects</Link></div><div className="mt-6 grid gap-4 md:grid-cols-2"><CourseCard course={courses[0]} /><CourseCard course={courses[1]} /></div></section>
      <section className="lg:col-span-3"><div className="mt-3 flex items-end justify-between"><div><SectionKicker>Progress tracking</SectionKicker><h2 className="font-display text-3xl tracking-[-.045em]">A clear view of your week.</h2></div><div className="hidden gap-5 text-sm md:flex"><span><strong className="text-[#18233B]">6</strong> day streak</span><span><strong className="text-[#18233B]">7h 42m</strong> study time</span></div></div><div className="mt-6 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><article className="chart-card"><div className="flex items-center justify-between"><div><h3 className="font-display text-xl tracking-[-.03em]">Weekly Activity</h3><p className="mt-1 text-sm text-[#65728A]">Minutes spent learning</p></div><Clock3 className="h-5 w-5 text-[#3B63E8]" /></div><div className="mt-7 h-[230px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={weeklyActivity} barSize={24}><CartesianGrid vertical={false} stroke="#EDF0F7" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "#65728A", fontSize: 12 }} /><YAxis hide /><Tooltip cursor={{ fill: "#F3F6FF" }} contentStyle={{ borderRadius: 12, border: "1px solid #E4E9F4", boxShadow: "0 8px 24px rgba(24,35,59,.08)" }} /><Bar dataKey="minutes" fill="#3B63E8" radius={[8, 8, 2, 2]} /></BarChart></ResponsiveContainer></div></article><article className="chart-card"><h3 className="font-display text-xl tracking-[-.03em]">Learning signals</h3><p className="mt-1 text-sm text-[#65728A]">A concise snapshot of your momentum.</p><div className="mt-7 space-y-5"><div className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EEF8F7] text-[#21867E]"><TrendingUp className="h-5 w-5" /></span><div><p className="text-sm font-bold">Accuracy is up 12%</p><p className="mt-0.5 text-xs text-[#65728A]">Compared with last week</p></div></div><div className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#FFF6EA] text-[#BA722B]"><BookOpen className="h-5 w-5" /></span><div><p className="text-sm font-bold">Classification needs review</p><p className="mt-0.5 text-xs text-[#65728A]">A short focused session will help</p></div></div><Link href="/quiz" className="btn-outline mt-2 w-full justify-center">Practice Classification <ArrowRight className="h-4 w-4" /></Link></div></article></div></section>
      <section id="analytics" className="lg:col-span-3"><div className="mt-8 grid gap-4 xl:grid-cols-2"><article className="chart-card"><h3 className="font-display text-xl tracking-[-.03em]">Performance Over Time</h3><p className="mt-1 text-sm text-[#65728A]">Average score by study week</p><div className="mt-7 h-[240px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={performanceData}><CartesianGrid vertical={false} stroke="#EDF0F7" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "#65728A", fontSize: 11 }} /><YAxis domain={[50, 100]} hide /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid #E4E9F4" }} /><Line type="monotone" dataKey="score" stroke="#3B63E8" strokeWidth={3} dot={{ r: 4, fill: "#3B63E8", strokeWidth: 2, stroke: "white" }} /></LineChart></ResponsiveContainer></div></article><article className="chart-card"><h3 className="font-display text-xl tracking-[-.03em]">Topic Accuracy</h3><p className="mt-1 text-sm text-[#65728A]">Where your study is strongest—and next.</p><div className="mt-7 space-y-5">{topicData.map(item => <div key={item.topic}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold text-[#53617A]">{item.topic}</span><strong>{item.score}%</strong></div><div className="h-2 rounded-full bg-[#E7EBF5]"><motion.div initial={{ width: 0 }} whileInView={{ width: `${item.score}%` }} viewport={{ once: true }} transition={{ duration: .6 }} className="h-full rounded-full bg-[#3B63E8]" /></div></div>)}</div></article></div></section>
    </div>
  </AppShell>;
}
